# Fig. 6.
python3 ../main.py \
--file_type='large' \
--common_path=../Experiment/MengXu-cryo/FL2U1 \
--training_path=../Datasets/MengXu-cryo/FL2U1-tif-norm \
--data_path_test=../Datasets/MengXu-cryo/FL2U1-tif-norm \
--patches_folder=../Datasets/MengXu-cryo/FL2U1_patches \
--patch_ratio=0.5 \
--patch_size=1024 \
--save_folder_name=experiment \
--version_folder_name=3x3_blind_spot \
--model=3x3_blind  \
--img_size=256 \
--batch_size=8 \
--max_epochs=100 \
--learning_rate=0.001 \
--loss_function='L2' \
--precision=16 \
--recursive_factor=10 \
--prepare_patch=1 \
--train=1 \
--test=1 \
--gpus=1